In [23]:
import pandas as pd
import sqlite3

In [24]:
df = pd.read_csv('../Data/processed/cleaned_ecommerce_sales.csv')

df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,order_year,order_month,order_month_name,order_day
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022,1,January,1
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022,1,January,2
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,Cod,6,2.5,644.35,2022,1,January,3
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022,1,January,4
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022,1,January,5

In [25]:
print("Rows and columns:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

Rows and columns: (5000, 16)

Columns:
['order_id', 'order_date', 'customer_id', 'product_category', 'region', 'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days', 'customer_rating', 'revenue', 'order_year', 'order_month', 'order_month_name', 'order_day']

Missing values:
order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
order_year          0
order_month         0
order_month_name    0
order_day           0
dtype: int64

In [26]:
conn = sqlite3.connect('../Data/ecommerce.db')

In [27]:
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

tables

              name
0  ecommerce_sales

In [28]:
df.to_sql(
    'ecommerce_sales',
    conn,
    index=False,
    if_exists='replace'
)

5000

In [29]:
pd.read_sql_query(
    "SELECT * FROM ecommerce_sales LIMIT 5;",
    conn
)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,order_year,order_month,order_month_name,order_day
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022,1,January,1
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022,1,January,2
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,Cod,6,2.5,644.35,2022,1,January,3
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022,1,January,4
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022,1,January,5

In [30]:
query = """
SELECT *
FROM ecommerce_sales
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,order_year,order_month,order_month_name,order_day
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022,1,January,1
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022,1,January,2
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,Cod,6,2.5,644.35,2022,1,January,3
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022,1,January,4
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022,1,January,5
5,10006,2022-01-06,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10,2022,1,January,6
6,10007,2022-01-07,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45,2022,1,January,7
7,10008,2022-01-08,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01,2022,1,January,8
8,10009,2022-01-09,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97,2022,1,January,9
9,10010,2022-01-10,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39,2022,1,January,10

In [31]:
query = """
SELECT COUNT(*) AS total_orders
FROM ecommerce_sales;
"""

pd.read_sql_query(query, conn)

   total_orders
0          5000